# ------------------------------
# ----- HTTP SERVER CONFIG -----
# ------------------------------
server {
    # -----------------------------
    # ---- BASIC CONFIGURATION ----
    # -----------------------------
    listen               80;
    server_name          localhost;
    root                 /app/web;
    index                index.php;
    client_max_body_size 20M;


    # -----------------------------
    # --- ROUTING CONFIGURATION ---
    # -----------------------------
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    # -----------------------------
    # ---- PHP RQUEST HANDLING ----
    # -----------------------------
    location ~ \.php$ {
        fastcgi_pass    php:9000;
        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include         fastcgi_params;
    }

    # -----------------------------
    # ---- ASSET CACHE CONFIG -----
    # -----------------------------
    # TODO


    # -----------------------------
    # --------- SECURITY ----------
    # -----------------------------
    location ~ /\. {
        deny all;
    }



    # -----------------------------
    # ----------- LOGS ------------
    # -----------------------------
    access_log  /dev/stdout;
    error_log   /dev/stderr;
}

# ------------------------------
# ----- HTTPS SERVER CONFIG ----
# ------------------------------
# TODO
